/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Categories: typeof import('./src/components/categories/Categories.vue')['default']
    ChargerIcon: typeof import('./src/components/icons/ChargerIcon.vue')['default']
    ChargerInformation: typeof import('./src/components/common/vehicle-detail/ChargerInformation.vue')['default']
    ChargerInput: typeof import('./src/components/common/charger-input/index.vue')['default']
    Container: typeof import('./src/components/base/Container.vue')['default']
    Header: typeof import('./src/components/base/Header.vue')['default']
    HistoryDetail: typeof import('./src/components/common/vehicle-detail/HistoryDetail.vue')['default']
    List: typeof import('./src/components/product/List.vue')['default']
    Loading: typeof import('./src/components/base/Loading.vue')['default']
    MyButton: typeof import('./src/components/common/my-button/index.vue')['default']
    MyInput: typeof import('./src/components/common/my-input/index.vue')['default']
    ProductInCart: typeof import('./src/components/cart/ProductInCart.vue')['default']
    ProductItem: typeof import('./src/components/product/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/base/Sidebar.vue')['default']
    Swiper: typeof import('./src/components/base/Swiper.vue')['default']
  }
}
